Review
RinatMef/blog-customizer pull request #2
Opened 2024-08-20 18:01 UTC by RinatMef

2024-08-21 09:16 UTC, SergeyK2004 requested changes
Добрый день! 

У вас получилась отличная работа:
* Полностью реализован функционал.
* Сайдбар закрывается по клику вне сайдбара
* Для условного добавления стилей используется библиотека `clsx`
* Типизированы все пропсы


Но есть пара моментов, который надо поправить:

- За состояние страницы отвечает компонент `App`, а за состояние формы компонент `ArticleParamsForm`. Нужно продумать логику передачи данных от `App` в форму и обратно.
- Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.
- Для дефолтных состояний статьи и формы используется `defaultArticleState`

Правки можно лучше остаются на ваше усмотрение:

- Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- Использовать один обработчик для событий `onChange` на элементах формы

Успешного рефакторинга!

2024-08-21 09:16 UTC, SergeyK2004 commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, { [styles.container_open]: isOpen })}
**Отлично:**

Здорово, что используете библиотеку `clsx`.

2024-08-21 09:16 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	isOpen,
**Надо исправить:**

Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния в родительский компонент не имеет смысла для нашего приложения. Состояние формы нужно описать в самом компонент `ArticleParamsForm`, а не передавать его из `App`, т.к. это состояние описывает именно `ArticleParamsForm`. В состоянии `App` должны хранится только данные о текущем отображении статьи.

2024-08-21 09:16 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [selectedContentWidth, setSelectedContentWidth] =
**Можно лучше:** 

Удобнее хранить все данные формы в одном стейте, а не создавать под каждое поле ввода свой стейт. Тогда единый обработчик для всех полей ввода будет выглядеть так:

```ts
const handleOnChange = (field: keyof ArticleStateType) => {
  return (value: OptionType) => {
    setState((prevState) => ({ ...prevState, [field]: value }));
  };
};
```

а его использование будет выглядеть так:

```ts
<Select
  title={'шрифт'}
  onChange={handleOnChange('fontFamilyOption')}
  selected={state.fontFamilyOption}
  options={fontFamilyOptions}
/>
```

2024-08-21 09:16 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		setSelectedFontFamily(null);
**Надо исправить:**

Настройки статьи по умолчанию описаны в объекте `defaultArticleState` в файле `constants/articleProps.ts`** стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.

2024-08-21 09:16 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useOutsideClickClose({
**Отлично:**
Хорошо, что используете кастомный хук

2024-08-21 09:16 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +								onClick={handleResetClick}
**Можно лучше:**

Обработчик сохранения данных должен вызываться при отправке формы и достаточно обработать только событие отправки формы. Не нужно вешать его на кнопку, нужно вызывать его при отправке формы

2024-08-21 09:16 UTC, SergeyK2004 commented on src/index.tsx
>  const App = () => {
**Можно лучше:**

Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-08-21 09:16 UTC, SergeyK2004 commented on src/index.tsx
> +	const [isOpen, setIsOpen] = useState(false);
**Надо исправить:**

Состояние открытия формы необходимо создавать и хранить в самой форме. Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния формы в родительский компонент не имеет смысла для нашего приложения.

2024-08-21 09:16 UTC, SergeyK2004 commented on src/index.tsx
> +		fontFamilyOption: OptionType | null;
**Надо исправить:**

Значения стилей не могут принимать null, стили всегда имеют какое-то конкретное значение, например значения по умолчанию.

2024-08-23 01:12 UTC, RinatMef commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [selectedContentWidth, setSelectedContentWidth] =
круто реализовано. Спасибо!

2024-08-23 07:53 UTC, SergeyK2004 approved these changes
Отлично. 
Работа принята, поздравляю.
Желаю успехов в дальнейшем обучении.

2024-08-23 07:53 UTC, SergeyK2004 commented on src/components/app/App.tsx
> +			<ArticleParamsForm articleStyles={setUserSettings} />
Можно было не создавать лишнюю сущность, функцию вызывающую функцию. Можно сразу передать в пропсы `setStyle`

2024-08-23 07:53 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +						onReset={handleResetClick}>
Отличная работа с событиями формы.

2024-08-23 15:48 UTC, closed without merging